version: "3.9"
services:
    api:
        container_name: api
        build: ./api
        ports:
            - "80:3000"
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo:4.2
        volumes:
            - "./mongo-volume:/data/db"
        ports:
            - "27017:27017"
            - "27018:27017"
