on:
  push:
    branches:
      - main
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: higebu/conventional-commits-parser-action@v1
        id: parser
      - run: |
          echo 'this step will be run if the commit type is `fix`'
        if: ${{ steps.paser.outputs.type == 'fix' }}
