name: API CI2

on:
    push:
        branches: [ master ]

jobs:
           
    Build-and-push-image:
        runs-on: ubuntu-latest
        outputs:
            FOO: ${{ steps.vars.outputs.sha_short }}
        steps:
            - uses: actions/checkout@v2
      
            - name: Set outputs
              id: vars
              run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
            - name: Check outputs
              run: echo ${{ steps.vars.outputs.sha_short }}
                  

    Deploy-To-SERVER:
        needs: Build-and-push-image
        env:
          Tag: ${{needs.Build-and-push-image.outputs.FOO}}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: multiple command
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.HOST_USER }}
                password: ${{ secrets.HOST_KEY }}
                envs: Tag
                script: |
                    echo $IMAGE_TAG
                    echo $Tag
